version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: simplebank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "6002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migration:/docker-entrypoint-initdb.d
    networks:
      - simplebank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplebank-app
    restart: unless-stopped
    environment:
      DB_SOURCE: postgresql://root:secret@postgres:6002/simple_bank?sslmode=disable
      SERVER_ADDRESS: 0.0.0.0:8080
      TOKEN_SYMMETRIC_KEY: "abcdefghijklmnopqrstuvwxyz123456"
      ACCESS_TOKEN_DURATION: 15m
    ports:
      - "6000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - simplebank-network
    volumes:
      - ./db/migration:/app/db/migration:ro

volumes:
  postgres_data:
    driver: local

networks:
  simplebank-network:
    driver: bridge
