// Code generated by "enumer -type=Currency -json"; DO NOT EDIT.

package util

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CurrencyName = "USDEURCAD"

var _CurrencyIndex = [...]uint8{0, 3, 6, 9}

const _CurrencyLowerName = "usdeurcad"

func (i Currency) String() string {
	if i < 0 || i >= Currency(len(_CurrencyIndex)-1) {
		return fmt.Sprintf("Currency(%d)", i)
	}
	return _CurrencyName[_CurrencyIndex[i]:_CurrencyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CurrencyNoOp() {
	var x [1]struct{}
	_ = x[USD-(0)]
	_ = x[EUR-(1)]
	_ = x[CAD-(2)]
}

var _CurrencyValues = []Currency{USD, EUR, CAD}

var _CurrencyNameToValueMap = map[string]Currency{
	_CurrencyName[0:3]:      USD,
	_CurrencyLowerName[0:3]: USD,
	_CurrencyName[3:6]:      EUR,
	_CurrencyLowerName[3:6]: EUR,
	_CurrencyName[6:9]:      CAD,
	_CurrencyLowerName[6:9]: CAD,
}

var _CurrencyNames = []string{
	_CurrencyName[0:3],
	_CurrencyName[3:6],
	_CurrencyName[6:9],
}

// CurrencyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CurrencyString(s string) (Currency, error) {
	if val, ok := _CurrencyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CurrencyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Currency values", s)
}

// CurrencyValues returns all values of the enum
func CurrencyValues() []Currency {
	return _CurrencyValues
}

// CurrencyStrings returns a slice of all String values of the enum
func CurrencyStrings() []string {
	strs := make([]string, len(_CurrencyNames))
	copy(strs, _CurrencyNames)
	return strs
}

// IsACurrency returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Currency) IsACurrency() bool {
	for _, v := range _CurrencyValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Currency
func (i Currency) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Currency
func (i *Currency) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Currency should be a string, got %s", data)
	}

	var err error
	*i, err = CurrencyString(s)
	return err
}
